services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.Backend.Dev
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_KEY_FOR_TOKEN=${SECRET_KEY_FOR_TOKEN}
      - ALGORITHM_FOR_TOKEN=${ALGORITHM_FOR_TOKEN}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    volumes:
      - .:/web
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    restart: always
