FROM python:3.11-slim
ENV PYTHONUNBUFFERED=1

# setting working directory
WORKDIR /web

# copying requirements.txt
COPY requirements.txt /web/requirements.txt

# installing all packages
RUN pip install --no-cache-dir -r requirements.txt

# copying complete backend
COPY . /web/

# Expose the application's port and debug port
EXPOSE 8002 5678

# run server with debugpy
CMD ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002", "--reload"]