services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.Backend.Dev
    ports:
      - "8002:8002"
      - "5678:5678"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/web
    command: python -m debugpy --listen 0.0.0.0:5678 -m uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    restart: always
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - ZITADEL_JWKS_URL=${ZITADEL_JWKS_URL}
      - ZITADEL_AUDIENCE=${ZITADEL_AUDIENCE}  
      - ZITADEL_ISSUER=${ZITADEL_ISSUER}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
